### ISSUE TITLE
BUg in GenericTicketConnector class

### ISSUE THREAD

**Issue by badman420** [ewsterrenburg/python-otrs#11]
Hi. I get this issue while trying to check GenericTicketConnector class - while I'm trying to access any methods of this class i get an 502 error, 'cos of incorrect endpoint server/otrs/nph-genericinterface.pl/Webservice/webservice_name. Trying to fix this issue leaves me to an empty response from server.

**Comment by ewsterrenburg** [comment]
@badman420
I do not think this is an issue with the python-otrs library, yet it seems to be related to OTRS itself. Therefore I will close this issue.  
You could try the OTRS mailing list or one of the OTRS related forums for help.
