### ISSUE TITLE
How to close user session?

### ISSUE THREAD

**Issue by mjducharme** [ewsterrenburg/python-otrs#13]
Hi,

Is there a way to close a user session via the script (i.e. de-authenticate)? I ask because I am using this for our monitoring software to create tickets in OTRS, it calls a separate copy of this script for every issue. It seems the session remains open for a certain amount of time until timeout, and so I start running into issues if many tickets are created in the same time period, I have to adjust the OTRS restrictions for maximum sessions per user, etc. I probably would not need to change these settings if I could add a line into the script to have it de-authenticate, closing the session, when it has finished doing its work on the tickets.

**Comment by ewsterrenburg** [comment]
As far as I know, the generic ticket connector only provides a SessionCreate operation an no operation to close/delete/remove a session ([documentation](http://otrs.github.io/doc/manual/admin/stable/en/html/genericinterface.html#genericinterface-connectors))

**Comment by mjducharme** [comment]
Thanks, I agree after reading that. That is an unfortunate limitation.
