### ISSUE TITLE
TicketGet with DynamicFields

### ISSUE THREAD

**Issue by mjducharme** [ewsterrenburg/python-otrs#14]
TicketGet with Dynamic fields is not working. The fields are returned by OTRS (i checked the web service debugger and it shows them in the output), but instead of the dynamic fields being available as child objects (like articles), dynamic fields are not added to the python object. I think there needs to be a:

```
def dynamic_fields(self):
    try:
        return self.childs['DynamicField']
    except KeyError:
        return []
```

in both class Ticket and class Article because both tickets and articles can have dynamic fields. I don't know the code well enough to know if a child map is also needed.

**Comment by mjducharme** [comment]
I submitted a patch that fixes this

**Comment by ewsterrenburg** [comment]
Thanks @mjducharme 
Was on holiday for a fews days, when I came back, it was both reported and fixed :)
