### ISSUE TITLE
Getting attachments from ticket

### ISSUE THREAD

**Issue by KVInventoR** [ewsterrenburg/python-otrs#2]
And how can you get the attachments from the ticket?

**Comment by KVInventoR** [comment]
objects.py

class Attachment(OTRSObject):
    XML_NAME = 'Attachment'

class Article(OTRSObject):
    XML_NAME = 'Article'
    CHILD_MAP = {'Attachment' : Attachment}

```
def attachment(self):
    try:
        return self.childs['Attachment']
    except KeyError:
        return []
```

class Ticket(OTRSObject):
    XML_NAME = 'Ticket'
    CHILD_MAP = {'Article' : Article}

```
def articles(self):
    try:
        return self.childs['Article']
    except KeyError:
        return []
```

//def ticket_get(self, ticket_id, get_articles=False, _args, *_kwargs):
def ticket_get(self, ticket_id, get_articles=False, get_attachments=False, _args, *_kwargs):

and query:
t = client.ticket_get(392974,get_articles=True,get_attachments=True)

**Comment by JocelynDelalande** [comment]
see #3

**Comment by ewsterrenburg** [comment]
Implemented, very similar to the lines suggested by @KVInventoR
