### ISSUE TITLE
Implement a Session Close ?

### ISSUE THREAD

**Issue by ErikWiesener** [ewsterrenburg/python-otrs#27]
Hi,
is it anyway possible to implement a sessio close() method? Because In my case many user with many tickets will create a Session and I don't want to change the Sessionlimitation on the OTRS Server.

Kind regards

Erik

**Comment by ewsterrenburg** [comment]
Unfortunately, this does not seem to be possible. Please see the discussion under https://github.com/ewsterrenburg/python-otrs/issues/13
