### ISSUE TITLE
better or more Ticketsearch operations

### ISSUE THREAD

**Issue by ErikWiesener** [ewsterrenburg/python-otrs#28]
Is it possible to get mor than the list of TicketIDs back, so maybe a JSON Dict with title, id, creator and so on ? Is it planned to implement such function ?

**Comment by ewsterrenburg** [comment]
@ErikWiesener 
The standard connectors supplied with OTRS do not provide the possibility to do so: the TicketSearch operation of the Ticket Connector of the OTRS GenericInterface returns a list of Ticket IDs that matches a predefined criteria. The only way to accomplish this would be to do a search first, followed by a loop that executes a TicketGet for the returned ID's and convert that to your desired format. This is however something you could easily do yourself and there's no point in making this part of python-otrs (besides the point that I'm guessing the series of looped requests is exactly the thing you want to avoid...)

What might be possible is the following:

1. Create your own connector in OTRS (where I would have no idea on how to implement this and neither whether it is even possible..) 
2. Fork python-otrs and write the files to make it work with your own connector (along the lines of the faq-connector).

ps: if you really need json, you might prefer [the rest interface](https://pyotrs.readthedocs.io/en/latest/readme.html#installation)
