### ISSUE TITLE
Make clear the maintenance status of this project

### ISSUE THREAD

**Issue by JocelynDelalande** [ewsterrenburg/python-otrs#3]
We (@oasiswork) do no longer maintain this project as we do no longer use python-otrs.

I would however be happy to add more commiters so that maintainers willing to adopt it can do it or to redirect users to another living fork.

@ajoaoff ? @KVInventoR ? @2xyo ?

**Comment by 2xyo** [comment]
I switched to [request tracker](https://www.bestpractical.com/rt/)... So, I'm not really interested to maintain this project anymore. 

But I hope someone else will maintain this project :)

**Comment by ewsterrenburg** [comment]
Although I don't plan on using this actively (more using it as a tool to familiarize myself with the soap-interface of OTRS), I could give this a shot if you like... @JocelynDelalande @oasiswork

**Comment by JocelynDelalande** [comment]
@ewsterrenburg Ok (sorry for delay, holidays...), I'm trying to transfer it to you, could you please rename or delete your fork _ewsterrenburg/python-otrs_ ? I cannot transfer the repo if you have something with that name on your account.

Thanks by advance.

**Comment by ewsterrenburg** [comment]
@JocelynDelalande Thanks. I have renamed it for now. Will delete this copy after the transfer is complete :).

**Comment by JocelynDelalande** [comment]
@ewsterrenburg Sorry, you even have to delete it now, gh says « ewsterrenburg already has a repository in the JocelynDelalande/python-otrs network » right now when I try to transfer.

**Comment by ewsterrenburg** [comment]
@JocelynDelalande Ok, just deleted it...

**Comment by JocelynDelalande** [comment]
@ewsterrenburg aaaaand… you host it :)

**Comment by ewsterrenburg** [comment]
@JocelynDelalande Thanks, I'll take good care of it :)
