### ISSUE TITLE
TicketSearch with mutiples States

### ISSUE THREAD

**Issue by victormangabeiro** [ewsterrenburg/python-otrs#34]
Hi guys,

How can I use TicketSearch with multiple states?

I tried:
`TicketSearch(States=['new','open'])`

But doesn't works :(

**Comment by ewsterrenburg** [comment]
@VictorGabrielRM 
Can you tell what result you are getting? I just tried exactly the same approach and it worked like a charm...

**Comment by ewsterrenburg** [comment]
No reaction. Will close this issue.
