### ISSUE TITLE
ticket PendingTime State

### ISSUE THREAD

**Issue by suntekma** [ewsterrenburg/python-otrs#35]
OTRS ticket State as a reminder, how to set the reminder datetime

t = Ticket(State='pending reminder',Priority='3 normal', Queue='IT Helpdesk',
               Title=computer + 'Add Administrator', CustomerUser=samid,TimeUnit='10',
               Type='Alert',Service='Alert::Administrator')

**Comment by engFelipeMonteiro** [comment]
fechar_ticket = Ticket(State='Contingenciado', PendingTime={'Diff':10080})
client.tc.TicketUpdate(ticket_id=busca_df[0], ticket=fechar_ticket, article=artigo_fechar)

*** otrs.client.SOAPError: TicketUpdate: Ticket->PendingTime parameter is invalid! (TicketUpdate.InvalidParameter)

**Comment by ewsterrenburg** [comment]
@suntekma @moita69 
You could using pendingTime without the capital at the start. However, there is another blocking issue here in OTRS itself :( See https://github.com/ewsterrenburg/python-otrs/issues/44
