### ISSUE TITLE
"out of memory" Exception while retrieving ticket with ~1G attachements

### ISSUE THREAD

**Issue by nstoeckigt** [ewsterrenburg/python-otrs#36]
When trying to retrieve a large ticket with the following code:
```
try:
»   ticket = client.ticket_get(tid, get_articles=True, get_dynamic_fields=True, get_attachments=True)
»   show_ticket_info(ticket)
except Exception as ex:
»   print("FAIL!\nEXCEPTION: %s" % (ex))
```
I get a 'out of memory' exception. The attachments are about 937MB and the whole SOAP response seems to be about 1.3GB.

**Comment by ewsterrenburg** [comment]
What steps have you taken to investigate this issue?
Is your server running out of memory or your client? And how much memory do you have available?
And does the request succeed using a SOAP client such as SoapUI?

**Comment by nstoeckigt** [comment]
In general all Requests (since 2 years) are successful - however this is the first time it failed and the only obvious difference is the whole size of the ticket and it's attachments. We are using the script - from which the above snippet is from - on a daily basis. I pinned the issue to the line where 'client.ticket_get()' is called.

----------------------------------------------------------------------
 System|total|used|free|shared|buff/cache|available
-|-----|------|-----|---------|-------------|------------
**OTRS-Server:**|
||19G|7,4G|12G|32M|2,0G|2,2G
**Client1:**|
||15G|2,6G|209M|967M|12G|12G
**Client2:**|
 ||7,5G|4,5G|1,0G|750M|1,9G|2,3G

Looks like the cache is not really used.

**Comment by ewsterrenburg** [comment]
Not clear where the issue is coming from, if it is still relevant and hard to replicate. Will close.
