### ISSUE TITLE
Invalid Webservice Name but returning SessionID

### ISSUE THREAD

**Issue by mike-mitchell** [ewsterrenburg/python-otrs#38]
I am getting the following error:
"BadStatusLine Exception when trying to reach https://cert2.corpnet.pl/otrs/nph-genericinterface.pl/Webservice/test.            Are you using the correct webservice name?"

But in the webservice debugger, there is a successful connection and the service is returning the correct session id.

"""<?xml version="1.0" encoding="UTF-8"?><soap:Envelope soap:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"><soap:Body><SessionCreateResponse xmlns="http://www.otrs.org/TicketConnector/"><SessionID>v0TKmhy5G8wwF0DLKDmCfk3xBL0ZTkrK</SessionID></SessionCreateResponse></soap:Body></soap:Envelope>"""

**Comment by ewsterrenburg** [comment]
@mike-mitchell 
Whatever the underlying reason, your server is passing back something that Python's urllib2 does not understand (wrong statuscode, wrong headers, ...?). 

I included the message regarding the webservice name as a hint (making a mistake in this name was the main reason I was getting this BadStatusLine error)
