### ISSUE TITLE
Ticket search with multiple StateIDs results in Traceback

### ISSUE THREAD

**Issue by nstoeckigt** [ewsterrenburg/python-otrs#40]
When trying a `ticket.search` like described in the [PyOTRS Docu](https://media.readthedocs.org/pdf/pyotrs/latest/pyotrs.pdf#section.3.7) I always ran into an Exception.
```
client.ticket_search(States=['new', 'open'],...)
*** AttributeError: 'str' object has no attribute 'to_xml'
```
also
```
client.ticket_search(StateIDs=[1, 4, 6, 7, 8, 10, 11],...)
*** AttributeError: 'int' object has no attribute 'to_xml'
```
What to do?

**Comment by mjducharme** [comment]
PyOTRS is not the same as python-otrs - two different frameworks
