### ISSUE TITLE
Missing ticket.merge

### ISSUE THREAD

**Issue by nstoeckigt** [ewsterrenburg/python-otrs#41]
Please add a functionality to merge tickets

**Comment by nstoeckigt** [comment]
It should somehow be possible → https://doc.otrs.com/doc/api/otrs/5.0/Perl/Kernel/System/Ticket.pm.html#TicketMerge

**Comment by ewsterrenburg** [comment]
@nstoeckigt 

It would be possible, yet it is not supported by the bundled ticket connector and would require a custom connector (see the final section this repository's README).
