### ISSUE TITLE
Question: ticket_search by multiple OwnerIDs

### ISSUE THREAD

**Issue by dizzydis** [ewsterrenburg/python-otrs#5]
In the ticket_search example, you show something like.. 

`otrs.ticket_search(OwnerIDs=1)`

How would I get a result set of tickets for multiple OwnerIDs?
I've tried a few things that didn't work and was just wondering if this feature was supported.

I have a workaround in place if not.

Thanks,

**Comment by ewsterrenburg** [comment]
@dayjavid 
This feature is not currently supported and at first sight it does not seem trivial to implement. 

The easy work-around would be to loop over the OwnerIDs in a loop and perform a series a requests, but my guess is you already considered that yourself :).

**Comment by dizzydis** [comment]
Yea I actually didn't even go that in depth.  We've written auto assignment logic so there's only a couple of owners that we auto reassign from.  Up until recently it was only one.  With the recent addition of the 2nd,  I just created two separate lists and concatenated them. 
Thanks for the reply though!
