### ISSUE TITLE
Sessions are dying very quickly

### ISSUE THREAD

**Issue by ryanbentley** [ewsterrenburg/python-otrs#7]
otrs.user_session_register(otrs_user, otrs_password)

this will work for a while, but after about 5 minutes we start getting:

  File "./app.py", line 1315, in manage
    otrs.user_session_register(otrs_user, otrs_password)
  File "/home/.env/local/lib/python2.7/site-packages/otrs/client.py", line 199, in user_session_register
    user_login=user)
  File "/home/.env/local/lib/python2.7/site-packages/otrs/client.py", line 185, in session_create
    Password=password)
  File "/home/.env/local/lib/python2.7/site-packages/otrs/client.py", line 142, in req
    raise SOAPError(unpacked[0])
otrs.client.SOAPError: SessionCreate: Authorization failing! (SessionCreate.AuthFail)

DebugLog error: Summary: TicketSearch.AuthFail Data : TicketSearch: Authorization failing!.
Sun Dec 13 10:42:18 2015    notice  GenericInterfaceProvider-01 SessionID: 'VnHfKTPDWzAdJKXcdsnWyhM0dYArODJJ' is invalid!!!
Sun Dec 13 10:42:13 2015    error   GenericInterfaceProvider-01 DebugLog error: Summary: TicketSearch.AuthFail Data : TicketSearch: Authorization failing!.
Sun Dec 13 10:42:13 2015    notice  GenericInterfaceProvider-01 SessionID: 'VnHfKTPDWzAdJKXcdsnWyhM0dYArODJJ' is invalid!!!
Sun Dec 13 10:42:01 2015    error   GenericInterfaceProvider-01 DebugLog error: Summary: TicketSearch.AuthFail Data : TicketSearch: Authorization failing!.
Sun Dec 13 10:42:01 2015    notice  GenericInterfaceProvider-01 SessionID: 'VnHfKTPDWzAdJKXcdsnWyhM0dYArODJJ' is invalid!!!
Sun Dec 13 10:41:46 2015    error   GenericInterfaceProvider-01 DebugLog error: Summary: TicketSearch.AuthFail Data : TicketSearch: Authorization failing!.
Sun Dec 13 10:41:46 2015    notice  GenericInterfaceProvider-01 SessionID: 'VnHfKTPDWzAdJKXcdsnWyhM0dYArODJJ' is invalid!!!
Sun Dec 13 10:41:41 2015    error   GenericInterfaceProvider-01 DebugLog error: Summary: TicketSearch.AuthFail Data : TicketSearch: Authorization failing!.
Sun Dec 13 10:41:41 2015    notice  GenericInterfaceProvider-01 SessionID: 'VnHfKTPDWzAdJKXcdsnWyhM0dYArODJJ' is invalid!!!
Sun Dec 13 10:41:41 2015    error   GenericInterfaceProvider-01 DebugLog error: Summary: TicketSearch.AuthFail Data : TicketSearch: Authorization failing!.
Sun Dec 13 10:41:41 2015    notice  GenericInterfaceProvider-01 SessionID: 'pdrgv5u3lZRUXB3t1tjgbyboG9ggBEcr' is invalid!!!
Sun Dec 13 10:41:37 2015    error   GenericInterfaceProvider-01 DebugLog error: Summary: TicketSearch.AuthFail Data : TicketSearch: Authorization failing!.
Sun Dec 13 10:41:37 2015    notice  GenericInterfaceProvider-01 SessionID: 'pdrgv5u3lZRUXB3t1tjgbyboG9ggBEcr' is invalid!!!
Sun Dec 13 10:41:36 2015    error   GenericInterfaceProvider-01 DebugLog error: Summary: TicketSearch.AuthFail Data : TicketSearch: Authorization failing!.
Sun Dec 13 10:41:36 2015    notice  GenericInterfaceProvider-01 SessionID: 'VnHfKTPDWzAdJKXcdsnWyhM0dYArODJJ' is invalid!!!
Sun Dec 13 10:41:31 2015    error   GenericInterfaceProvider-01 DebugLog error: Summary: TicketSearch.AuthFail Data : TicketSearch: Authorization failing!.
Sun Dec 13 10:41:31 2015    notice  GenericInterfaceProvider-01 SessionID: 'VnHfKTPDWzAdJKXcdsnWyhM0dYArODJJ' is invalid!!!
Sun Dec 13 10:41:23 2015    error   GenericInterfaceProvider-01 DebugLog error: Summary: TicketSearch.AuthFail Data : TicketSearch: Authorization failing!.
Sun Dec 13 10:41:23 2015    notice  GenericInterfaceProvider-01 SessionID: 'VnHfKTPDWzAdJKXcdsnWyhM0dYArODJJ' is invalid!!!
Sun Dec 13 10:41:23 2015    error   GenericInterfaceProvider-01 DebugLog error: Summary: TicketSearch.AuthFail Data : TicketSearch: Authorization failing!.
Sun Dec 13 10:41:23 2015    notice  GenericInterfaceProvider-01 SessionID: 'pdrgv5u3lZRUXB3t1tjgbyboG9ggBEcr' is invalid!!!
Sun Dec 13 10:41:14 2015    error   GenericInterfaceProvider-01 DebugLog error: Summary: TicketSearch.AuthFail Data : TicketSearch: Authorization failing!.
Sun Dec 13 10:41:14 2015    notice  GenericInterfaceProvider-01 SessionID: 'VnHfKTPDWzAdJKXcdsnWyhM0dYArODJJ' is invalid!!!
Sun Dec 13 10:41:14 2015    error   GenericInterfaceProvider-01 DebugLog error: Summary: TicketSearch.AuthFail Data : TicketSearch: Authorization failing!.
Sun Dec 13 10:41:14 2015    notice  GenericInterfaceProvider-01 SessionID: 'pdrgv5u3lZRUXB3t1tjgbyboG9ggBEcr' is invalid!!!
Sun Dec 13 10:41:01 2015    error   GenericInterfaceProvider-01 DebugLog error: Summary: TicketSearch.AuthFail Data : TicketSearch: Authorization failing!.
Sun Dec 13 10:41:01 2015    notice  GenericInterfaceProvider-01 SessionID: 'VnHfKTPDWzAdJKXcdsnWyhM0dYArODJJ' is invalid!!!
Sun Dec 13 10:41:01 2015    error   GenericInterfaceProvider-01 DebugLog error: Summary: TicketSearch.AuthFail Data : TicketSearch: Authorization failing!.
Sun Dec 13 10:41:01 2015    notice  GenericInterfaceProvider-01 SessionID: 'pdrgv5u3lZRUXB3t1tjgbyboG9ggBEcr' is invalid!!!
Sun Dec 13 10:40:38 2015    error   GenericInterfaceProvider-01 DebugLog error: Summary: TicketSearch.AuthFail Data : TicketSearch: Authorization failing!.
Sun Dec 13 10:40:38 2015    notice  GenericInterfaceProvider-01 SessionID: 'pdrgv5u3lZRUXB3t1tjgbyboG9ggBEcr' is invalid!!!
Sun Dec 13 10:40:38 2015    error   GenericInterfaceProvider-01 DebugLog error: Summary: TicketSearch.AuthFail Data : TicketSearch: Authorization failing!.
Sun Dec 13 10:40:38 2015    notice  GenericInterfaceProvider-01 SessionID: 'VnHfKTPDWzAdJKXcdsnWyhM0dYArODJJ' is invalid!!!

What is happening here?

**Comment by ewsterrenburg** [comment]
You could check the system log of your otrs installation, maybe there are some hints on what is going on...

**Comment by ewsterrenburg** [comment]
Issue most likely not related to python-otrs but related to the environment (dynamic ip-adress or something similar?), so closing this issue for now. Can be reopened if it shows otherwise.
